language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master